services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
  server:
    build: .
    ports:
      - 3010:8080
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?schema=public
      - BROKER_URL
      - FRONTEND_URL
      - MAILER_TRANSPORT
      - SECRET
    depends_on:
      - db
