name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ GITHUB_REPOSITORY#*/ }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Read node from package.json
      id: package-node-version
      uses: culshaw/read-package-node-version-actions@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ env.DOCKER_REPOSITORY }}:${{ steps.package-node-version.outputs.version }}
        cache-from: type=registry,ref=${{ env.DOCKER_REPOSITORY }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_REPOSITORY }}:buildcache,mode=max
