name: Docker Image CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Get version from package.json after release step
      id: extractver
      run: echo "::set-output name=version::$(npm run get-version --silent)"
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        builder: ${{steps.buildx.outputs.name}}
        push: true
        tags: ${{secrets.DOCKER_HUB_USERNAME}}/auth:${{steps.extractver.outputs.version}}
        cache-from: type=registry,ref=${{secrets.DOCKER_HUB_USERNAME}}/auth:buildcache
        cache-to: type=registry,ref=${{secrets.DOCKER_HUB_USERNAME}}/auth:buildcache,mode=max
